# Generated by Django 3.2.5 on 2021-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211006_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(blank=True, to='users.ExerciseTag'),
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='repetitions',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='sets',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercisetag',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='users.Exercise'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
