# Generated by Django 3.2.5 on 2021-10-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211006_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstance',
            name='repetitions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
