# Generated by Django 3.2.5 on 2021-10-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_workouttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='types',
            field=models.ManyToManyField(blank=True, to='users.WorkoutType'),
        ),
    ]
