# Generated by Django 3.2.5 on 2021-10-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_workout_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='profile',
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.baseuser'),
            preserve_default=False,
        ),
    ]
