# Generated by Django 3.2.5 on 2021-10-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211008_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='sets',
        ),
        migrations.AddField(
            model_name='exerciseinstance',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.exerciseinstance')),
            ],
        ),
    ]
