# Generated by Django 3.2.5 on 2021-10-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_exercisetag_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='set',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='types',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workouttype',
            name='workouts',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseInstance',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutType',
        ),
    ]
