# Generated by Django 3.2.5 on 2021-11-09 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='value',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
