from django.urls.conf import path
from .views import (
    add_exercise,
    CreateType,
    CreateTag,
    add_type,
    search_workout,
    search_exercise,
    workouts,
    add_set,
    edit_set,
    delete_set,
    add_instance,
    save_instance_and_add_set,
    edit_instance,
    delete_instance,
    render_list,
    add_workout,
    detail_workout,
    edit_workout,
    delete_workout,
)

urlpatterns = [
    path('', workouts, name='workouts'),
    path('add', add_workout, name='add-workout'),
    path('<int:pk>/add', edit_workout, name='edit-workout'),
    path('<int:pk>/delete', delete_workout, name='delete-workout'),
    path('<int:pk>/list', render_list, name='render-list'),
    path('<int:pk>/detail', detail_workout, name='detail-workout'),
    path('search', search_workout, name='search-workout'),
    path('<int:pk>/instances/add', add_instance, name='add-instance'),
    path('<int:pk>/instances/add2',
         save_instance_and_add_set, name='add-instance-set'),
    path('instances/<int:pk>/edit', edit_instance, name='edit-instance'),
    path('instances/<int:pk>/delete', delete_instance, name='delete-instance'),
    path('instances/<int:pk>/sets/add', add_set, name='add-set'),
    path('instances/search', search_exercise, name='search-exercise'),
    path('sets/<int:pk>/edit', edit_set, name='edit-set'),
    path('sets/<int:pk>/delete', delete_set, name='delete-set'),
    path('types/add', add_type, name='add-type'),
    path('tags/add', CreateTag.as_view(), name='add-tag'),
    path('exercises/add', add_exercise, name='add-exercise'),
]
