# Generated by Django 3.2.5 on 2021-10-19 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_auto_20211012_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='workouts.Tag'),
        ),
        migrations.AlterField(
            model_name='set',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.exerciseinstance'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
