# Generated by Django 3.2.5 on 2021-11-09 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20211019_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='exerciseinstance',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='workouttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise'),
        ),
    ]
