# Generated by Django 3.2.5 on 2021-11-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20211109_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='comment',
        ),
        migrations.AddField(
            model_name='exerciseinstance',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
